// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://autixypkmyfzypmqnsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dGl4eXBrbXlmenlwbXFuc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTgyODYsImV4cCI6MjA1NjE3NDI4Nn0.vWRAphkntuxDJbgSxsleei5R-gG0NwGLQIbtXUEjEyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);